### ISSUE TITLE
Update to latest bgfx

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#101]
The current version being used hasn't been updated in a while so would be good to do that.

Also the local hack with

```C++
bgfx::nativeContext()
```
Can now be removed and switch to use this https://github.com/bkaradzic/bgfx/commit/72be9be87d027fa2746bbc1b63c9beb1700cc371

**Comment by theWatchmen** [comment]
I can look into this if you'd like :)

**Comment by emoon** [comment]
That would be great :)

Also I'm currently doing a *big* rewrite in the Rust branch. It's not read to go to master yet but you should be able to work on master/sub branch of master for now.

Also (like I wrote above) just accept the latest bgfx/bx code as is and then fix the compile errors afterwards but using the new data provided in the commit.

**Comment by emoon** [comment]
Also notice that you may want to update to latest https://github.com/bkaradzic/bx also

**Comment by theWatchmen** [comment]
Cool, I should be able to work on it in the next couple of days

**Comment by emoon** [comment]
Nice :) It's not a major hurry really but I like to try to keep the libs I depend on up to date :+1:

**Comment by emoon** [comment]
Any update on this one? Working with branch from master should be just fine now also.

**Comment by emoon** [comment]
This has been done now
