### ISSUE TITLE
Window doesn't resize correctly

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#153]
When resizing the window the drawing doesn't update correctly. This is because the correct size isn't being set to bgfx when we do the resize.

**Comment by emoon** [comment]
Updated to minifb 0.6.0 in https://github.com/emoon/ProDBG/commit/697cc356fa18ca20de39683d78125f19e302cb3c which now support ``get_size()` to get the window size which should make it easier to implement this.

**Comment by kondrak** [comment]
Fixed by https://github.com/kondrak/ProDBG/commit/a8d91b63605b08cf10720c17894df93f51ec8798
