### ISSUE TITLE
Logo and Icon

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#174]
A logo and Icon would be nice to have for ProDBG. While not vastly important it's nice to give the program an identity.

# Good logos/icons

![rsz_visual-studio-logo-7](https://cloud.githubusercontent.com/assets/350822/15804663/ff358d9c-2b10-11e6-87a1-2dbeaa7a95e7.jpg)

The new Visual Studio Logo is clean and easy to remember and non cluttered.

![unity-logo](https://cloud.githubusercontent.com/assets/350822/15804770/80546cba-2b14-11e6-9085-197ef88a1d64.png)

Also the Unity logo is nice.

# Bad logos/icons

![p4](https://cloud.githubusercontent.com/assets/350822/15804671/4f98b322-2b11-11e6-9275-eb19f3c2b497.png)

The P4 logo is all over the place with very "screaming" colors.

<img width="256" alt="xcode-icon" src="https://cloud.githubusercontent.com/assets/350822/15804674/7d2eaa80-2b11-11e6-8e1b-89c50a1fae42.png">

While I understand Appels intent I think this logo is too detailed. I would like something simpler.

# Direction

The logo should also play good with the default color scheme which will be in the direction of Black Ink

![black_ink](https://cloud.githubusercontent.com/assets/350822/15804689/ebc114a6-2b11-11e6-8ec1-c27bf16fc389.jpg)

Their logo looks like this: The default color scheme comes back in this one with some extra tones given to it. I would prefer the ProDBG still to be more clean (like VS) but colors should come back.

![blackink_logo](https://cloud.githubusercontent.com/assets/350822/15804695/138230c4-2b12-11e6-8b1b-989a2d90621c.jpg)

Also if possible I would like the icon to somewhat reflect that it's a debugger. While I don't hate the idea of having something in the direction of a "bug" as icon looking here https://www.google.se/search?q=debugger&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiB_-z6y5DNAhVhM5oKHQodAcUQ_AUIBygB&biw=2276&bih=1119#tbm=isch&q=debugger+logo I really don't see much things I like.

Still trying to tie back to what the tool actually does would be nice.

**Comment by memononen** [comment]
<img width="384" alt="screen shot 2016-06-06 at 00 41 08" src="https://cloud.githubusercontent.com/assets/5249992/15808382/743d6cf4-2b7f-11e6-9f2e-6c957cb20d15.png">
My dyslexic mind has always read the project name a bit wrong. Though, using that logo might require you to change the name to "The ProDBG" ;)

**Comment by emoon** [comment]
@memononen Thanks :) Yeah there is already a debugger for Sony platforms (PS2/PS3/etc) called ProDG which is pretty much spot on to what you say :). The with my name it's close to that because it draws inspiration from it :)

**Comment by Jake-Shadle** [comment]
The logo that was chosen has not been added to the readme, critical this gets fixed! ;)

**Comment by emoon** [comment]
@Jake-Shadle Fixed in https://github.com/emoon/ProDBG/commit/6e78f21e862547382a28bc7d6ca8b87a8aecbda4 (I may want to reduce the size of it though :)

**Comment by emoon** [comment]
Closing as done :)
