### ISSUE TITLE
Allow redocking existing dock

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#187]
It should be possible to redock existing views with other views. When dragging a window titlebar with the mouse a blue preview overlay should be presented when the mouse is moving to potential docking locations. 

![drag_view_support](https://cloud.githubusercontent.com/assets/350822/16177868/de6a1c08-3638-11e6-8ca6-75642f96a375.png)

If the user moves back to the mouse over the original view the operation is canceled.

**Comment by emoon** [comment]
Something that would be nice (related to #189) 
![tabs_docking](https://cloud.githubusercontent.com/assets/350822/16499693/d28c5a1e-3f01-11e6-889e-9312e0344a0a.jpg)

Is to allow docking to highlight like this and it will add as a tab instead.

This is a semi layout of where things would dock given the location within an existing view

![docking_mouse_ranges](https://cloud.githubusercontent.com/assets/350822/16500394/9c252e30-3f04-11e6-855e-14ce51f0a4f1.jpg)

**Comment by SlNPacifist** [comment]
Such system only allows further partitioning of docks. Imagine you have workspace like this:
```
_________________
|                |
|                |
|________________|
|       |        |
|       |        |
|_______|________|
```
and you want workspace like this
```
_________________
|                |
|                |
|________________|
|       |        |
|_______|________|
|________________|
```
How do you achieve this with described docking system?

**Comment by emoon** [comment]
That is a good point but then imagine if you have something like this:

```
_________________
|                |
|                |
|________________|
|   |   |        |
|   |   |        |
|___|___|________|
```

Should it become like this then?

```
_________________
|                |
|                |
|________________|
|   |   |        |
|___|___|________|
|________________|
```

And would that way only wok on "edges" of the workspace? I wonder how it would behave if you try to do this in the middle of the workspace as it would need to move more things away.

**Comment by SlNPacifist** [comment]
Well, I tried to implement drop zones to support "out of bounds" docking, but it looked pretty messy. One place could refer to several possible places and I had no obvious way to pick one of them. I guess we'll stick with current model.
By the way, once this issue is finished, will it be better to replace "Split horizontally", "Split vertically" menu items with simple "Create"? When user picks plugin, he will use same interface to pick place for it.

**Comment by emoon** [comment]
Agreed so lets stick with the current model as I think it work just fine.

Having a "Create" as you say would be nice but I think it would be good to have it as an additional item in the popup and have the same interface for selecting the location. I still (for now) would like to keep the split horizontal/vertical as it's a bit faster if you know how you want your split directly instead of actually having to drag/pointing it to the correct location. 

Also in #183 the idea is to be aware of where the user is doing the splitting so the new window appears under the mouse.

**Comment by emoon** [comment]
Implemented
