### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by SlNPacifist** [emoon/ProDBG#192]
Cargo.toml says there should be a build script: `build = "build.rs"`. However, no `build.rs` file is present.

```
slnpacifist@slnpacifist-TWH:~/projects/ProDBG$ cargo build
   Compiling prodbg_main v0.1.0 (file:///home/slnpacifist/projects/ProDBG)
   Compiling cfg-if v0.1.0
   Compiling bitflags v0.3.3
   Compiling ws2_32-sys v0.2.1
   Compiling log v0.3.4
   Compiling kernel32-sys v0.2.1
   Compiling inotify v0.1.12
   Compiling libloading v0.2.0
error: couldn't read "build.rs": No such file or directory (os error 2)
Build failed, waiting for other jobs to finish...
error: Could not compile `prodbg_main`.

To learn more, run the command again with --verbose.
```

**Comment by xpicox** [comment]
Did you clone the repository with the --recursive flag?

**Comment by kondrak** [comment]
To build ProDBG use proper scripts in the ./scripts folder, this will generate all the necessary files for you. See Readme for instructions for specific platform.

**Comment by SlNPacifist** [comment]
I tried to build project on Ubuntu 16.04. Readme gives no instructions on building it under linux (only says it builds but crashes on start) so I tried `cargo build`.

**Comment by emoon** [comment]
Ok.

I will need to update the readme regarding Linux. Linux builds and is somewhat working (you can't still debug but that is in line with the other platforms)

@ashemedai has been doing some work on Linux recently so perhaps he can update the readme on exactly what is needed.

You can also look in the https://github.com/emoon/ProDBG/blob/master/.travis.yml which builds on Linux and the dependencies that are needed.
