### ISSUE TITLE
Implement plugin API generator

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#196]
Writing bindings and glue code for it is boring and it would be much nicer to auto-generate a huge part of it.

Inspiration can be taken from this https://github.com/capnm/Khronos_XML_API/blob/master/egl.xml

The idea is then to define the APIs ProDBG support in some format like this and generate the files like

https://github.com/emoon/ProDBG/blob/master/api/include/pd_ui.h
https://github.com/emoon/ProDBG/blob/master/api/rust/prodbg/src/ui_ffi.rs

A bit tricker would be https://github.com/emoon/ProDBG/blob/master/api/rust/prodbg/src/ui.rs but might be doable if the generator is written in such a way that it's easy to do those things.

Likely there should be a set of "helpers" for various backends like C generation, Rust and later on for bindings that targets Lua.

**Comment by kondrak** [comment]
Somewhat related to #165, maybe I should hold off with doing it and look at this one instead...

**Comment by emoon** [comment]
Getting this done would be great!

The way I see is that this is a custom tool (written in Rust) that will run first when you compile the project and then output a number of files. Setting this up so everything depends on it correct is possible in Tundra (at least for C++ stuff but should be fine for Rust also but need to take a look at it)

This can still be started without having it within the full chain.

1. Figure out a good format for the input data (should it be xml? json, etc)
2. Start with generating the pd_ui.h from it.
3. Start with generating something like ui_ff.rs

**Comment by emoon** [comment]
Also generating this would be nice: https://github.com/emoon/ProDBG/blob/master/src/native/ui/imgui_ffi.cpp but might be a bit tricky.

**Comment by emoon** [comment]
Crate that will be used for this is being worked on over here https://github.com/kondrak/codespawn

**Comment by kondrak** [comment]
" I also realised there are already some code that does something similar to what we need with the code generator later on https://github.com/emoon/ProDBG/blob/master/units.tools.lua#L30 and this is then being used here https://github.com/emoon/ProDBG/blob/master/units.libs.lua#L346 "

**Comment by emoon** [comment]
Closing this as this is mainly done even if we may use it for more things.
