### ISSUE TITLE
Move bgfx to git submodule

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#199]
As we have the source unmodified now (I think) it should be possible to use it as a submodule instead.

**Comment by emoon** [comment]
Something you want to take a look at @theWatchmen ?

**Comment by theWatchmen** [comment]
@emoon You read my mind :) I should be able to look at it relatively soon

**Comment by emoon** [comment]
@theWatchmen Seems that you got beat to it ;)

**Comment by v3n** [comment]
Hehe, whoops. ;)

**Comment by emoon** [comment]
@v3n No worries. Thanks for the contrib! :)

**Comment by v3n** [comment]
I've got a pending fix for the OS X build errors, waiting on the upstream merge for a fix I submitted.

**Comment by emoon** [comment]
Now the CI is catching the error as well (I'm likely going to setup some own CI for Mac as travis is waay too slow but right now better than nothing)
