### ISSUE TITLE
View dosen't redock sometimes

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#220]
On the https://github.com/emoon/ProDBG/tree/viewdock sometimes when dragging a view/dock it doesn't get redocked. 

Repo

1. ``Create two docks``` (as seen in image)
2. ``Drag left dock over to the right one so it becomes green.``
3. ``Now move the mouse back towards the left side and release```

Notice that even if the area is highlighted the dock will not be connected to the new area.

![dock_bug](https://cloud.githubusercontent.com/assets/350822/16558029/7356306c-41e3-11e6-80f2-e7f2524858ec.jpg)

**Comment by SlNPacifist** [comment]
That's actually visualization bug. Since this drag-and-drop does nothing, overlay should not have been shown. Fixed by corresponding PR.

**Comment by emoon** [comment]
It should be connected when it looks like this (also see ref video)

**Comment by emoon** [comment]
Closing this as this is somewhat similar to #222
