### ISSUE TITLE
Show new dock location directly

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#222]
On the https://github.com/emoon/ProDBG/tree/viewdock branch

When moving the mouse dragging a dock over to another dock the new preview placement should be show directly. Right now you have to move into the side before it to happen. Also see the preview video I sent

![dock_mouse](https://cloud.githubusercontent.com/assets/350822/16557759/f6fec110-41e1-11e6-9c9f-eddec2592174.jpg)

**Comment by SlNPacifist** [comment]
@emoon Check the behavior with latest changes. I guess this should be fixed now.

**Comment by emoon** [comment]
It's better but doesn't fully work correct yet.

![no_corner_drag](https://cloud.githubusercontent.com/assets/350822/16574168/51b75b90-427c-11e6-8f40-e70b144a274d.jpg)

If you are trying to drag to these areas nothing shows up. It's only in the middle that it works.

**Comment by SlNPacifist** [comment]
In that case I cannot reproduce this bug. Here is how it looks for me: https://drive.google.com/file/d/0B_NiJJG73au8ZTZXSVpEWjlzWFE/view?usp=sharing. Could it be that overlay is not shown but when you drop dock workspace is changed?

**Comment by emoon** [comment]
If you try to drag to the upper right corner of the "Plugin 1" area. Does that work?

**Comment by SlNPacifist** [comment]
There are no drop zones in upper right and lower right corners, so overlay is not shown.

**Comment by emoon** [comment]
Did you look at the ref movie I emailed you?

**Comment by SlNPacifist** [comment]
Yes, I did

**Comment by emoon** [comment]
I would like it to behave like that (which also have drop zones in the corners)

**Comment by SlNPacifist** [comment]
Are [these](https://drive.google.com/file/d/0B_NiJJG73au8NHRtbG9EM1NCRk0/view?usp=sharing) drop zones okay for you? I can't get exact drop zones from video.

**Comment by emoon** [comment]
Sent you a new movie. Hopefully it makes it more clean.

**Comment by emoon** [comment]
Ok. I will fix this myself instead.

**Comment by SlNPacifist** [comment]
@emoon are you talking to Sabirshah right now? If so, can we chat directly?

**Comment by emoon** [comment]
Yes I am

**Comment by emoon** [comment]
@SlNPacifist You can use this https://gitter.im/emoon/ProDBG and drop me a private message if you want.

**Comment by emoon** [comment]
Works as I want it now. Thanks!
