### ISSUE TITLE
Draging doesn't work after window resize

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#223]
Repro
1. `Create some views`
2. `Resize the the main window`

Notice that it's no longer possible to drag docks around and the top ones are not reachable.

**Comment by SlNPacifist** [comment]
Cannot reproduce. Found another issue in code that could be the reason for that: there is "PreDocking" state and in order to leave it user have to move mouse for more then 5px away in single frame (weird logic). Could this "PreDocking" state be a reason for described bug?

**Comment by kondrak** [comment]
@SlNPacifist which platform are you testing on? I fixed a couple of bugs here (not related to viewdock) which only happened on a single platform (and even a single distribution, so either release only or debug only), so this may hint you where to look. AFAIK @emoon is testing primarily on Mac.

**Comment by emoon** [comment]
![screen shot 2016-07-04 at 14 15 10](https://cloud.githubusercontent.com/assets/350822/16560148/d51affa4-41f1-11e6-94d9-10069c1415ac.png)

After I resize you can see the window labes for the views are almost gone (Mac tested)

**Comment by SlNPacifist** [comment]
@kondrak I work on Ubuntu 16.04 64bit and ProDBG never behaves like this here. Most likely, this is ImgUI-related bug. Is this bug connected with tabs somehow? We only added drawing tabs and removed 4px right and bottom border for Views (borders are calculated by Splits now).

**Comment by emoon** [comment]
Alright. I will have to investigate this one myself then. 
On Jul 4, 2016 14:34, Vyacheslav <notifications@github.com> wrote:@kondrak I work on Ubuntu 16.04 64bit and ProDBG never behaves like this here. Most likely, this is ImgUI-related bug. Is this bug connected with tabs somehow? We only added drawing tabs and removed 4px right and bottom border for Views (borders are calculated by Splits now).

**Comment by emoon** [comment]
Looked at this and it seems to be a minifb bug on Mac. I think the size that is returned back doesn't take the windowbar (or something like that) into account. If I hardcode some value into the code it works as expected.

**Comment by emoon** [comment]
Switching Qt and C++ (for now, will be reevaluated when there are some good Rust bindings for Qt) so closing.
