### ISSUE TITLE
Show preview area on same docking location

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#224]
On the On the https://github.com/emoon/ProDBG/tree/viewdock branch

Repro:

1. ``Create the same layout as show in image``
2. ``Drag the lower plugin to the lower part of the top plugin``

Notice that no preview is being show. I would assume the reason is because the doc will just be in the same place but it would be better to show it as it make the UX more consistent with what is being shown when docks are being dragged around.

![drag_dock_same_location](https://cloud.githubusercontent.com/assets/350822/16559440/3fcd65a8-41ed-11e6-8dc5-33522265b9ce.jpg)

**Comment by SlNPacifist** [comment]
What about undo/redo? Should this unchanged state be saved to undo/redo stack?

**Comment by emoon** [comment]
As this action will not generate any result (it's only a visual thing) undo/redo stack should be unaffected
