### ISSUE TITLE
Support byte view in memory view

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#232]
Hex view

![mem1](https://cloud.githubusercontent.com/assets/350822/16577535/3070c920-4296-11e6-996b-81be29f0f41a.JPG)

Signed

![byte_signed](https://cloud.githubusercontent.com/assets/350822/16577550/3d736b64-4296-11e6-8d07-8f09a077e274.JPG)

Unsigned

![byte_unsigned](https://cloud.githubusercontent.com/assets/350822/16577559/44f18308-4296-11e6-941e-7539c23b09c9.JPG)

**Comment by SlNPacifist** [comment]
Closed by 5a340d4
