### ISSUE TITLE
Memory delta changes in memory view

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#237]
Start state

![before_mem_change](https://cloud.githubusercontent.com/assets/350822/16577929/2d1d2118-4298-11e6-9a2e-c07e63ee3c8d.JPG)

The user steps the debugger and one byte has changed since last update and should be displayed in different color (here red)

![after_mem_change](https://cloud.githubusercontent.com/assets/350822/16577957/46a7e816-4298-11e6-9bdb-f491a12ff371.JPG)

**Comment by SlNPacifist** [comment]
What events should trigger this behavior (replace previous data with current and request update)? It is not obvious from their names.

**Comment by emoon** [comment]
If the plugins gets a event called ```EVENT_SET_EXCEPTION_LOCATION``` it means that the user has stepped in the debugger and then the memory may have changed. The plugin should then request the current viewed memory again and do a "diff" with the current memory and change the color of those values that have changed.

**Comment by emoon** [comment]
This is supported in the old memory plugin https://github.com/emoon/ProDBG/blob/master/src/plugins/hex_memory/hex_memory_plugin.cpp so you can look at the code there (this is written in C though)

**Comment by SlNPacifist** [comment]
Closed by 5a340d4
