### ISSUE TITLE
Edit support in memory view

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#238]
It should be possible to edit memory. This is for both data and ascii changes:

Data

![edit](https://cloud.githubusercontent.com/assets/350822/16577985/7152e502-4298-11e6-9253-413a036534f8.JPG)

Edit text

![edit_text](https://cloud.githubusercontent.com/assets/350822/16577988/77eae9e6-4298-11e6-919b-ea1cffc523d0.JPG)

**Comment by SlNPacifist** [comment]
What about decimal mode and float mode? Should we support editing memory in decimal mode and how should editor behave?
In hexadecimal mode we can edit every digit in its representation (4 bits) independently. But in decimal mode editing each digit seems odd to me. Visual Studio 2015 Community (I use it as a reference for user interface) only allows editing in hexadecimal mode.

**Comment by emoon** [comment]
Yeah lets do the same (only allow edit in hex)

**Comment by SlNPacifist** [comment]
Closed by 5a340d4
