### ISSUE TITLE
Rewrite memory view in Rust

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#239]
Code is here https://github.com/emoon/ProDBG/tree/master/src/plugins/hex_memory This code https://github.com/emoon/ProDBG/blob/master/src/plugins/disassembly/src/lib.rs can be looked to see how to use this from Rust

This may also need to add some required code in the Rust wrapper of imgui.

**Comment by SlNPacifist** [comment]
Closed by 5a340d4
