### ISSUE TITLE
Show invalid memory regions in memory view

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#242]
Should work in Visual Studio

![invalid_memory](https://cloud.githubusercontent.com/assets/350822/16578252/d173e728-4299-11e6-95a7-17a504d108e7.JPG)

If the memory view has requested some memory which it doesn't get back it may because the target is unable to read it and thus the memory viewer should display it as ```?? ??``` (also this memory shouldn't be possible to edit)

**Comment by SlNPacifist** [comment]
Closed by 5a340d4
