### ISSUE TITLE
Select memory mode, u8/u16/etc, signed/unsigned

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#243]
![mem1](https://cloud.githubusercontent.com/assets/350822/16578549/70bedaf8-429b-11e6-906d-1f4ce8010516.JPG)

Should be some drop-down after the columns drop down.

**Comment by SlNPacifist** [comment]
Well, button + popup were meant to be "drop-down". I couldn't find anything like drop-down in ImGui.

**Comment by SlNPacifist** [comment]
Should endianness be included in this drop-down? For now, it has 14 variants (2 for floats, 4 for hex, 8 for signed/unsigned int). With endiannes it will be 28 variants, which could become pretty messy.

**Comment by emoon** [comment]
I would suggest having a bunch of different drop-downs/combo boxes like one for size,  one for display typ and then a checkbox for endian.

**Comment by SlNPacifist** [comment]
Closed by 5a340d4
