### ISSUE TITLE
Support different colums sizes in memory view

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#244]
1/2/4/8/16/32/64 - auto

![columns](https://cloud.githubusercontent.com/assets/350822/16578577/8ffd9c9c-429b-11e6-89bb-84c10dff1c0a.JPG)

**Comment by SlNPacifist** [comment]
Does not it make more sense to use "Bytes per line" metric instead of "Columns"? 64 8-byte floats are way too big for any monitor, but 64 1-byte hex are less than today's monitor width.

**Comment by emoon** [comment]
I think columns is a better metric because as a user it's more intuitive I would say to think "I want my values in 8 columns regardless of type" 

Also it's worth to remember that the current font we use is fairly big and the user can set a smaller font. For example comment out this line: https://github.com/emoon/ProDBG/blob/master/src/native/ui/bgfx/imgui_setup.cpp#L135 to get the default 8x8 font which allows you to see more.

**Comment by SlNPacifist** [comment]
Closed by 5a340d4
