### ISSUE TITLE
Ability to turn data/text on/off in memory view

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#245]
No data

![no_data](https://cloud.githubusercontent.com/assets/350822/16578644/f17e344a-429b-11e6-830a-78c1868ecd3e.JPG)

No text

![no_ascii](https://cloud.githubusercontent.com/assets/350822/16578648/f6613868-429b-11e6-891c-786ab6f534bc.JPG)

**Comment by SlNPacifist** [comment]
Closed by 5a340d4
