### ISSUE TITLE
Window height can be 0 on first frame

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#260]
This happens for @SlNPacifist which is quite weird. Needs to be investigated why.

**Comment by belkiss** [comment]
I have the same issue, it even crashes on startup:
thread '<main>' panicked at 'arithmetic operation overflowed', src/prodbg/main/src/windows.rs:598

Workarounded it by testing win_size.1 before substracting the statusbar size:

`        if win_size.1 > 0 {
            win_size.1 -= self.statusbar.get_size() as usize;
        }`

**Comment by emoon** [comment]
Yeah, I will have to look at why this happens. Thanks for the report!

**Comment by emoon** [comment]
Fixed in https://github.com/emoon/ProDBG/commit/a9456cb35fe5653a073ba8e069d53a6030287692
