### ISSUE TITLE
Assert on startup if current working dir does not contain "data" 

### ISSUE THREAD

**Issue by belkiss** [emoon/ProDBG#262]
ProDBG asserts on startup if it's launched from a folder which does not contain the "data" subfolder.
In my case, I cd'ed to t2-output/linux-gcc-debug-default and ran ./prodbg.

The assert is:

`prodbg: /home/belkiss/RD/ProDBG/src/native/external/imgui/imgui_draw.cpp:1185: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion 0' failed.`

Maybe the folder presence could be checked earlier?

Thanks

**Comment by emoon** [comment]
Yeah I guess the instructions are a bit unclear.

You should stand in the root and run ``t2-output/linux-gcc-debug-default/prodbg`` I will make instructions more clear.

**Comment by emoon** [comment]
Fixed in https://github.com/emoon/ProDBG/commit/5a2154f7ba18471d5832e877a322641edc9a3506
