### ISSUE TITLE
Improve plugin load error messages

### ISSUE THREAD

**Issue by SlNPacifist** [emoon/ProDBG#272]
Sometimes plugins that exist in saved layout cannot be loaded. During ProDBG start every plugin that could not be loaded just removes its dock. It would be better to do next:
- show error message in plugin's dock
- show buttons like "reload, close" in plugin's dock
- do not remove or change info for plugin's dock so that user can close ProDBG, fix issue (like return previous version of plugin), start ProDBG and continue his work.

This is a better behavior for #266 
@emoon what do you think?

**Comment by emoon** [comment]
Sounds good!

**Comment by emoon** [comment]
As this has changed so much this issue isn't really relevant anymore.
