### ISSUE TITLE
Add SymbolLookup Request

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#283]
It should be possible for views to request an address from a symbol. Say if a user writes an symbol in the address field of a memory view it should be possible to check which address the symbol is located at (or show an error)

**Comment by SlNPacifist** [comment]
Where can I get more info on symbols? I don't know a good place to start reading about what symbol is, what kind of symbols could be, etc.

**Comment by emoon** [comment]
Yeah so this isn't implemented yet. To do this one has to add an event (request) that sends a string to the backend and returns an address (if the symbol was found) otherwise returns the request (in this case I think it's best to have the string being sent back as "id" until we have a proper request API)

**Comment by SlNPacifist** [comment]
I wanted to pick this task but don't have enough knowledge about symbols. I guess symbols could be pretty much anything (functions, constants, shared fields of memory) and API should respond with maximum we can give about a symbol with address being just common for all of them.

**Comment by emoon** [comment]
Symbol also depends on the context of where the debugger is. Say you have a function with variable called ``test``. ``test`` is placed somewhere in memory (stack or heap) so when a request for ``test`` comes that address should be sent back. Now in C/C++ you can have shadow variables so it's legal to have a global test as well. In this case it becomes a bit more tricky and needs to be investigated how current debuggers deal with this. I guess testing it in MSVC would be possible (there you can for example write ``test`` as the address and it gets re-translated to a memory location)

**Comment by emoon** [comment]
This has now been implemented.
