### ISSUE TITLE
Bug when docking view

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#301]
See this movie for repro https://dl.dropboxusercontent.com/u/5205843/viewdock_bug.mov (and use included project file) for the layout to start from (rename to .json and place in data/)

[current_project.txt](https://github.com/emoon/ProDBG/files/426690/current_project.txt)

**Comment by SlNPacifist** [comment]
First container in split has same child twice:
```json
"Container": {
    "docks": [
        0,
        0
    ],
    "active_dock": 0
}
```
which is the reason to this behavior.

Need to find out how could same child be appended to container twice.

**Comment by emoon** [comment]
I see. I don't know the exact steps I did to make this happen but I was just adding a bunch of views, re-docking them and then it happen.

**Comment by emoon** [comment]
Maybe we can try to have some "randomizing" unit/integration test for this? That you randomize some views (with a given random seed), move them around, then verify (in code) that everything is looking correct. If it's not it's possible to use the same random seed again and try to repro the problem.

**Comment by SlNPacifist** [comment]
I'm not fan of randomized tests and we do not really have infrastructure for this. I think this concrete bug can be resolved by inspecting code.

**Comment by emoon** [comment]
Switching Qt and C++ (for now, will be reevaluated when there are some good Rust bindings for Qt) so closing.
