### ISSUE TITLE
Rewrite ThreadsPlugin in Rust

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#307]
https://github.com/emoon/ProDBG/blob/master/src/plugins/threads/threads_plugin.cpp

**Comment by xilec** [comment]
Hello,

I'm trying to rewrite this view to rust.
And I find some confusing case to me:
According [this](https://github.com/emoon/ProDBG/blob/master/src/plugins/threads/threads_plugin.cpp#L41) line of C++:

    if (PDRead_find_array(reader, &it, "threads", 0) == PDReadStatus_NotFound)
        return;

returning array can be not found, but in [rust api](https://github.com/emoon/ProDBG/blob/master/api/rust/prodbg/src/read_write.rs#L295) method `Reader::find_array` return non-`Option` iterator
It seems like missing case in rust API for imgui. Is it?

**Comment by SlNPacifist** [comment]
This looks like an error. Rust implementation does not use result of external `read_find_array` call at all:

```
    pub fn find_array(&self, id: &str) -> ReaderIter {
        let s = CFixedString::from_str(id).as_ptr();
        let mut t = 0u64;

        unsafe {
            ((*self.api).read_find_array)(transmute(self.api), &mut t, s, 0);
        }

        ReaderIter {
            reader: self.clone(),
            curr_iter: t,
        }
    }
```

**Comment by emoon** [comment]
@xilec Hi, thanks for looking at this! You can see an example of how its being used here https://github.com/emoon/ProDBG/blob/master/src/plugins/disassembly/src/lib.rs#L49

**Comment by xilec** [comment]
Ok. Thanks.

**Comment by emoon** [comment]
Also @xilec if possible when starting on working on an issue please drop a small post on it that you are looking at it. Just to make sure not several people are doing something at the same time :)

**Comment by emoon** [comment]
Also as @SlNPacifist pointed out the implementation for the ``find_array`` code isn't the best but you should be able to use it as is and if the API gets changed it will be easy to fix it later on.
