### ISSUE TITLE
Using RPC for plugin API

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#329]
After considering https://github.com/emoon/ProDBG/issues/327 I have started to think in general of how the the plugins work and esp the on the UI front.

The way plugins work today has largely been influenced by how plugins work in Lightwave. (C API, Provides a structs with function pointers for plugins, dll based)

While this works fine if you write native plugins and also add bindings to other languages it has some drawbacks:
- Glue code
- Problems of bringing up new languages.
- Needs to be an dll

I'm thinking there might be a better way to solve this. One way would be to have all plugins only listen in to a RPC interface over network. One way would be to use JSON as it's widley supported everywhere today. @SlNPacifist pointed out that values is JSON is always doubles and that would be annoying for pointer values (would need to use strings on BASE64 encoding, might be fine?)

What I see with this is:

Pros:
- Possibility to web apps to talk directly with ProDBG without needing an to be an dll.
- Better separation
- Less Glue code.

Cons:
- Performance? (If all plugins would be local I would expect the socket sending between the plugins would be very fast though)
- Unknown territory (for me)

Would really like feedback on this!

**Comment by xilec** [comment]
RPC communication between plugins also is choosen in xi-editor([link](https://github.com/google/xi-editor/pull/43)). 
Actually I don't see deeply, but I hope it will help.

**Comment by emoon** [comment]
Yeah. I have been following the project for a while (it might be a good fit for ProDBG later on with large source files) 

After seeing the Xi presentation at Rust Conf I have become even more interested in looking into this approach.
