### ISSUE TITLE
Disassembly error

### ISSUE THREAD

**Issue by Kalmalyzer** [emoon/ProDBG#337]
This set of code bytes:

![image](https://cloud.githubusercontent.com/assets/1208699/21484402/329b46be-cb92-11e6-8b14-57ad19b2021e.png)

results in this set of instructions:

![image](https://cloud.githubusercontent.com/assets/1208699/21484409/44866b38-cb92-11e6-8e82-e849a4e1ae06.png)

The CMP instruction should have an immediate operand of 4, but it shows as 0 in the disassembly instead.

**Comment by Kalmalyzer** [comment]
Hmm. It is possible that this only happens if the instruction is at the end of a "disassembly window": it was the last instruction in view. Once I single-stepped past that instruction, the disassembler fetched another chunk of code bytes & disassembled - and now the cmp.l instruction displays properly:

![image](https://cloud.githubusercontent.com/assets/1208699/21484426/9735402a-cb92-11e6-8b20-89f797670fde.png)

**Comment by emoon** [comment]
Ah. It's likely that it doesn't fetch enough data or such at the last instruction because the way it works is that the debugger will only request a certain range of disassembly right now and it's fairly primitive.

**Comment by emoon** [comment]
Closing this for now as going to do lots of various work in this area
