### ISSUE TITLE
Implement context menu

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#67]

**Comment by ocornut** [comment]
Out of curiosity.. I am not sure how you are drawing the line between using ImGui and modifying it to use fancier rendering output or the recent docking improvement.  Latest screenshot shows a context menu:

![b6g-1sbiqaaec1n png large](https://cloud.githubusercontent.com/assets/8225057/5606548/d6c5b5c6-942b-11e4-9d9e-bac0882f999a.png)

Are you content with using ImGui for certain things and something else for menus, or would it be of any use if I implemented menus in ImGui ? (standard & popup/context menus).

**Comment by emoon** [comment]
I'm not really sure where to draw the line.

In this case (to start with) it was just simpler to use standard popup but that will likely not work on Linux (because I need to depend on GTK or something else)

The main issue with popups is that they need to work outside the main windows so you would need to open up a new window(s) in order for it to be rendered.

Having this in ImGui would (as stated above) be for the best but right now I'm going to stick with OS version but I need to solve it for Linux at some point also.

The way the docking system works is that it's quite agnostic to the windows. All it does is to have a handle to a window and then it sets a own rect for it. Later on I do a update loop that just "forces" the ImGui windows in place.

This isn't a very nice solution currently but does the job for the time being.

**Comment by emoon** [comment]
For Windows and Linux having menus (in this case top menu) would be good. On Mac I would likely use the regular one as it's very standard for Mac apps and it's not also "connected" to the Main Window as it is on Windows for example.

**Comment by ocornut** [comment]
Cool. I'll try to bounce menus up in my own todo list - I guess it wouldn't hurt.
Rendering the menus outside the main host window is an interesting problem but not necessary to solve. Notice in Windows is you right-click at the bottom of your desktop the menu popup high enough to fit its items. And I assume it also allows scrolling (although you rarely see it under Windows). So it would be an easier solution to just do that.

( If the actual imgui window can't be moved/resized you can set a flag in Begin() to hide the "resizing" thing in the lower-left corner. )

**Comment by emoon** [comment]
Yeah I guess that is true that you can just restrict it to the bounds of the current window.

In general the way I see it also (with regards to fancier rendering in ImGui) is that I will still for "stock" ImGui for as long as I can (I have some changes to it but they are quite minor) but there will likely be one point were I will just decide to leave it as is when doing more changes and integrations will become too painful.

**Comment by ocornut** [comment]
Understood, that makes sense. From my perspective I'm happy to provide support and see how far this can go with ImGui because that will raise and push for improvements. Don't hesitate to make bold requests or fork it or drop it as you see fit in the future.

**Comment by emoon** [comment]
Alright. Sounds good :)

**Comment by emoon** [comment]
Something that I know I will need in the future is variable size fonts and support for AA in them (I have actually dropped NanoVG now because it really added more work than it was worth and I only used the text rendering of it)

**Comment by emoon** [comment]
Maybe I should add proper request(s) instead :)

**Comment by ocornut** [comment]
Would using stb_truetype be enough ? (as in, prerendering fonts into textures)

**Comment by emoon** [comment]
Yeah I think that should be fine. NanoVG is also using pre-rendered font for the text rendering but I'm not sure if it does something more "smart" when actually using it for the rending (i.e. if text is scaled it might do some better filter than just regular bilinear)

**Comment by emoon** [comment]
Moved to https://prodbg.phoreplay.com/T7
