### ISSUE TITLE
OSX 10.9.5 Blank (black) window

### ISSUE THREAD

**Issue by wtfbbqhax** [emoon/ProDBG#73]
Trying to use under OSX 10.9.5 (Xcode installed, clang, etc..)

Compiles successfully, but ProDBG is otherwise unresponsive. (See Screenshot)

![screen shot 2015-02-17 at 17 58 31](https://cloud.githubusercontent.com/assets/7323455/6239102/98d05bfc-b6ce-11e4-96a3-d772d911e285.png)

Tried:

"Open and run executable" -  prompts for file to open but doesn't do anything.
"Open source" - prompts for file to open but doesn't do anything else.

--

Checking "Console" I don't have any logs from ProDBG.

--

Is there any other information I can provide you to help?

**Comment by bigmonachus** [comment]
FWIW, I pulled and compiled on Windows and got the same thing. I just assumed that Windows is not fully supported yet

**Comment by wtfbbqhax** [comment]
Attached dtruss trace (note its not actually a jpeg file, wget the link and open in text editor).

![prodbg_dtruss](https://cloud.githubusercontent.com/assets/7323455/6242860/90677104-b704-11e4-8bda-d4acff3f6d4d.jpeg)

**Comment by emoon** [comment]
Hi,

As stated in the readme:

"Status
Major redesign of the ProDBG is currently happening so be aware that not much is currently working"

You can right click on the window and do splitting/open windows and such currently as I'm focusing on fixing up the docking/window system and once that is done (tracked here https://prodbg.phoreplay.com/T1) 

I will start bringing back so basic debugging works again.

**Comment by wtfbbqhax** [comment]
Cool, can't wait.
--
Split Vertical and Split Horizontal don't appear to do anything either.

Thanks.

**Comment by emoon** [comment]
Hum.. that sounds weird.. Can you select any views in the Splits or does the menu only show Split Vert/Horz?

**Comment by wtfbbqhax** [comment]
Nope. Right clicking produces the "Split Horizontally / Split Veritically" menu. Actually clicking "Split <>" leaves me with the same blank/black window with no changes.

**Comment by emoon** [comment]
ok.. If you start from terminal (in the root ProDBG directory) with the command: t2-output/macosx-clang-debug-default/ProDBG.app/Contents/MacOS/prodbg

do you get anything in the menus then?

**Comment by wtfbbqhax** [comment]
Yes, that does work.

- Cool

**Comment by emoon** [comment]
Alright. I think the issue then is that loading of the plugins doesn't work from all locations (it's path relative) so that is something I will have to look into later.

**Comment by emoon** [comment]
Closing this as there is a work-around for the issue
