### ISSUE TITLE
Build status broken

### ISSUE THREAD

**Issue by pfalcon** [emoon/ProDBG#76]
Build status icons as presented in README lead to 404, e.g. https://camo.githubusercontent.com/34bf2e43f6d50897838064f7c633ceb290567fce/687474703a2f2f7a656e69632e6f72673a383131312f6170702f726573742f6275696c64732f6275696c64547970653a2869643a50726f4442475f4c696e7578292f73746174757349636f6e

**Comment by emoon** [comment]
Yeah this is a known issue because I have switched from TeamCity to Buildbot (0.90) which doesn't support build status yet so I will just link to the builedbot page instead.

Thanks for the report.
