### ISSUE TITLE
build isue on OS X

### ISSUE THREAD

**Issue by nyotis** [emoon/ProDBG#82]
![screen shot 2015-07-20 at 11 47 16](https://cloud.githubusercontent.com/assets/658719/8773515/1df707c6-2ed5-11e5-99eb-52dd503aba87.png)

**Comment by emoon** [comment]
Cut'n'paste from the readme

How to compile and run on Mac

Building the code on Mac requires that Clang is installed on your system. The easiest way to do this is to get Xcode and install the commandline tools.

After doing that open a terminal and run scripts/mac_build_debug.sh and you should have an executable that you can open in t2-output/macosx-clang-debug-default/ProDBG.app

**Comment by nyotis** [comment]
![screen shot 2015-07-20 at 12 01 09](https://cloud.githubusercontent.com/assets/658719/8773758/080dd848-2ed7-11e5-82f0-344b86db2cf5.png)

**Comment by theWatchmen** [comment]
You have to launch it from the main folder: it should read
`scripts/mac_build_debug.sh`

**Comment by nyotis** [comment]
OK
