### ISSUE TITLE
Split Horizontally and Vertically are reversed

### ISSUE THREAD

**Issue by gwihlidal** [emoon/ProDBG#83]
Right clicking in a pane and selecting Split Horizontally will perform a vertical split. Right clicking in a pane and selecting Split Vertically will perform a horizontal split.

**Comment by theWatchmen** [comment]
Is this on the standard UI or the "old" one (ImGui vs Native)?

**Comment by emoon** [comment]
Moved over here https://prodbg.phoreplay.com/T193
