### ISSUE TITLE
Implement API Wrapper Generator

### ISSUE THREAD

**Issue by emoon** [emoon/ProDBG#89]
In order to support #88 we need to have a wrapper around the C API. This will also be needed for other backends. To make this easier there will be a tool that parses the C API headers and generates binds for each backend.

**Comment by emoon** [comment]
Thinking about using https://github.com/eliben/pycparser for this. Should hopefully be good enough.

**Comment by jdm** [comment]
Is the goal of this issue different than https://github.com/crabtw/rust-bindgen ?

**Comment by emoon** [comment]
@jdm Slightly. While rust-bindgen generates a direct mapping to the to the C API I also want to generate a more high-level.

For example

```Rust
pub struct CPDReaderAPI {
    private_data: *mut c_void,
    read_u8: extern fn(data: *mut c_void),
}
```

This is the code that is being generate (or  similar) by rust-bindgen but I also want something like this

```Rust
pub struct Reader {
    c_reader_api: *mut CPDReaderAPI,
}

impl Reader {
    pub fn read_u8(&self) {
        unsafe {
            ((*self.c_reader_api).read_u8)((*self.c_reader_api).private_data)
        }
    }
}
```

New when you have some code in a plugin written in rust it would look like

```Rust
fn some_fun(reader: &Reader)
{
   let data = reader.read_u8();
}
```

Also having it parsed into some data it would make it easier to generate binding later on for whatever language one wants to support for plugins.

**Comment by emoon** [comment]
I decided to do this manually for now. Hopefully that will be good enough
